# 02 - Case Representation

Notebook ini menampilkan hasil representasi kasus dari PDF menjadi data terstruktur.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path('..').resolve()
DATA_DIR = PROJECT_ROOT / 'data'
RAW_PDF_DIR = DATA_DIR / 'raw' / 'pdf'
RAW_TEXT_DIR = DATA_DIR / 'raw' / 'text'
PROCESSED_DIR = DATA_DIR / 'processed'
EVAL_DIR = DATA_DIR / 'eval'
RESULTS_DIR = DATA_DIR / 'results'

In [2]:
cases_df = pd.read_csv(PROCESSED_DIR / 'cases.csv')
print('Jumlah kasus:', len(cases_df))
cases_df.head()

Jumlah kasus: 40

,case_id,no_perkara,tanggal_putusan,pengadilan,jenis_perkara,file_pdf,file_txt,nama_file_asli,jumlah_halaman,jumlah_kata,...,problem_text,ringkasan_fakta,argumen_hukum,solution_text,amar_lainnya,catatan_amar,lama_pidana,lama_pidana_bulan,solution_label,text_full
0,case_001,1104/Pid.B/2025/PN.Tng,NaN,Pengadilan Negeri Tangerang,Pidana Umum - Pencurian,data/raw/pdf/case_001.pdf,data/raw/text/case_001.txt,putusan_1104_pid.b_2025_pn_tng_20260626204755.pdf,25,7748,...,p u t u s a n nomor 1104/pid.b/2025/pn tng dem...,P U T U S A N\nNomor 1104/Pid.B/2025/PN Tng\nD...,"Menimbang, bahwa Terdakwa diajukan ke persidan...",MENGADILI:\n1. Menyatakan Terdakwa M. ALAM ABD...,MENGADILI:\n1. Menyatakan Terdakwa M. ALAM ABD...,MENGADILI:\n1. Menyatakan Terdakwa M. ALAM ABD...,2 tahun,24.0,Pidana Penjara > 12 Bulan,P U T U S A N\nNomor 1104/Pid.B/2025/PN Tng\nD...
1,case_002,1134/Pid.B/2025/PN.Tng,NaN,Pengadilan Negeri Tangerang,Pidana Umum - Pencurian,data/raw/pdf/case_002.pdf,data/raw/text/case_002.txt,putusan_1134_pid.b_2025_pn_tng_20260626210203.pdf,43,14182,...,p u t u s a n nomor 1134/pid.b/2025/pn tng dem...,P U T U S A N\nNomor 1134/Pid.B/2025/PN Tng\nD...,"Menimbang, bahwa Para Terdakwa diajukan ke per...",MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,3 tahun,36.0,Pidana Penjara > 12 Bulan,P U T U S A N\nNomor 1134/Pid.B/2025/PN Tng\nD...
2,case_003,1184/Pid.B/2025/PN.Tng,NaN,Pengadilan Negeri Tangerang,Pidana Umum - Pencurian,data/raw/pdf/case_003.pdf,data/raw/text/case_003.txt,putusan_1184_pid.b_2025_pn_tng_20260626205721.pdf,13,4072,...,p u t u s a n nomor 1184/pid.b/2025/pn tng dem...,P U T U S A N\nNomor 1184/Pid.B/2025/PN Tng\n“...,"Menimbang, bahwa telah didengar pembelaan seca...",M E N G A D I L I\n1. Menyatakan Terdakwa WIDO...,M E N G A D I L I\n1. Menyatakan Terdakwa WIDO...,M E N G A D I L I\n1. Menyatakan Terdakwa WIDO...,2 tahun 6 bulan,30.0,Pidana Penjara > 12 Bulan,P U T U S A N\nNomor 1184/Pid.B/2025/PN Tng\n“...
3,case_004,1185/Pid.B/2025/PN.Tng,NaN,Pengadilan Negeri Tangerang,Pidana Umum - Pencurian,data/raw/pdf/case_004.pdf,data/raw/text/case_004.txt,putusan_1185_pid.b_2025_pn_tng_20260626204526.pdf,15,4428,...,p u t u s a n nomor 1185/pid.b/2025/pn tng dem...,P U T U S A N\nNomor 1185/Pid.B/2025/PN Tng\n“...,"Menimbang, bahwa telah didengar pembelaan seca...",M E N G A D I L I\n1. Menyatakan Terdakwa I RA...,M E N G A D I L I\n1. Menyatakan Terdakwa I RA...,M E N G A D I L I\n1. Menyatakan Terdakwa I RA...,1 tahun 7 bulan,19.0,Pidana Penjara > 12 Bulan,P U T U S A N\nNomor 1185/Pid.B/2025/PN Tng\n“...
4,case_005,118/Pid.B/2026/PN.Tng,NaN,Pengadilan Negeri Tangerang,Pidana Umum - Pencurian,data/raw/pdf/case_005.pdf,data/raw/text/case_005.txt,putusan_118_pid.b_2026_pn_tng_20260626210553.pdf,17,5295,...,p u t u s a n nomor 118/pid.b/2026/pn tng demi...,P U T U S A N\nNomor 118/Pid.B/2026/PN Tng\nDE...,"Menimbang, bahwa atas pledooi Terdakwa melalui...",MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,MENGADILI:\n \n \n \n \n \n \n \n \n \n1. Meny...,10 bulan,10.0,Pidana Penjara 7-12 Bulan,P U T U S A N\nNomor 118/Pid.B/2026/PN Tng\nDE...

In [3]:
important_cols = ['case_id','no_perkara','tanggal_putusan','terdakwa','pasal','tindak_pidana','lama_pidana','solution_label']
cases_df[important_cols].head(10)

,case_id,no_perkara,tanggal_putusan,terdakwa,pasal,tindak_pidana,lama_pidana,solution_label
0,case_001,1104/Pid.B/2025/PN.Tng,NaN,M. ALAM ABDURRAHMAN ALIAS ALAM BIN,Pasal 363 ayat (1) ke-4 dan ke-5 KUHPidana; Pa...,Pencurian dalam keadaan memberatkan,2 tahun,Pidana Penjara > 12 Bulan
1,case_002,1134/Pid.B/2025/PN.Tng,NaN,Dodi Saputra Bin Eefendi; Ovit Sukron Alias Ov...,Pasal 55 ayat (1) ke-1 Kitab Undang-Undang Huk...,Penadahan,3 tahun,Pidana Penjara > 12 Bulan
2,case_003,1184/Pid.B/2025/PN.Tng,NaN,Wido Elce Putra als Wido Bin Cepik,Pasal 363 Ayat (1) Ke-3 KUHP; Pasal\n363 Ayat ...,Penurian\ndengan pemberatan,2 tahun 6 bulan,Pidana Penjara > 12 Bulan
3,case_004,1185/Pid.B/2025/PN.Tng,NaN,Rajes Saputra Als Rajeg Bin Siswanto; Muhamad ...,Pasal 480 Ke-1 KUHP; Pasal 55 Ayat (1) Ke-1 KU...,Turut serta melakukan Menjual barang yang sepa...,1 tahun 7 bulan,Pidana Penjara > 12 Bulan
4,case_005,118/Pid.B/2026/PN.Tng,NaN,Marsin Bin Osip,Pasal 54 ayat (1) KUHP,Pencurian\ndalam keadaan memberatkan,10 bulan,Pidana Penjara 7-12 Bulan
5,case_006,1194/Pid.B/2025/PN.Tng,NaN,ELIN Binti MUSTAHIL (alm),Pasal 363 Ayat (1) ke-3 dan Ke-4 KUHPidana,Pencurian\ndalam keadaan memberatkan,3 tahun,Pidana Penjara > 12 Bulan
6,case_007,1198/Pid.B/2025/PN.Tng,NaN,"Muhamad, Shandika Bin Moch Hidayat; Muhamad Ir...",Pasal 365 ayat (2) ke-1 dan ke-2 KUHPidana; Pa...,Pencurian dengan kekerasan\nyang dilakukan pad...,4 tahun,Pidana Penjara > 12 Bulan
7,case_008,1255/Pid.B/2025/PN.Tng,NaN,Wira Winata als Wira Bin Sair Nian,Pasal 365 Ayat (2) Ke – 1 KUHP; Pasal 53 Ayat ...,percobaan melakukan kejahatan mengambil barang...,4 tahun,Pidana Penjara > 12 Bulan
8,case_009,1260/Pid.B/2025/PN.Tng,NaN,Hairul Azib Als Iyunk Bin Danil Setiawan,Pasal 363 ayat (1) ke-3 KUHPidana,Pencurian Dalam Keadaan Memberatkan,1 tahun,Pidana Penjara 7-12 Bulan
9,case_010,1276/Pid.B/2025/PN.Tng,18\nSeptember 2025,FAHMI FAHREZY Bin SURYADI,"Pasal 363 Ayat (1) ke-3,4 dan 5 KUHP; Pasal 36...","mengambil barang sesuatu, yang seluruhnya atau...",1 tahun 6 bulan,Pidana Penjara > 12 Bulan

In [4]:
cases_df['solution_label'].value_counts()

solution_label
Pidana Penjara > 12 Bulan       33
Pidana Penjara 7-12 Bulan        5
Pidana Penjara <= 6 Bulan        1
Pidana Tidak Teridentifikasi     1
Name: count, dtype: int64